version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1-stretch

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - setup_remote_docker
      - run: make
