# permissions for end users to edit lokistacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lokistack-editor-role
rules:
- apiGroups:
  - loki.openshift.io
  resources:
  - lokistacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loki.openshift.io
  resources:
  - lokistacks/status
  verbs:
  - get
