---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: loki
    newName: docker.io/grafana/loki
    newTag: 2.1.0

commonLabels:
  app.kubernetes.io/name: loki
  app.kubernetes.io/provider: openshift

resources:
  - distributor-deploy.yaml
  - distributor-grpc-service.yaml
  - distributor-http-service.yaml
  - ingester-deploy.yaml
  - ingester-http-service.yaml
  - ingester-grpc-service.yaml
  - gossip-ring-service.yaml
  - querier-deploy.yaml
  - query-frontend-deploy.yaml
  - query-frontend-grpc-service.yaml
  - query-frontend-http-service.yaml

configMapGenerator:
  - name: loki-config
    files:
      - ../../../internal/manifests/loki-config.yaml

