---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: query-frontend
  name: loki-query-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: query-frontend
      loki.grafana.com/gossip: "true"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: query-frontend
        loki.grafana.com/gossip: "true"
    spec:
      containers:
      - image: loki
        name: loki-query-frontend
        args:
        - -target=query-frontend
        - -config.file=/etc/loki/config/loki-config.yaml
        - -log.level=error
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /metrics
            port: 3100
            scheme: HTTP
          periodSeconds: 30
        ports:
        - containerPort: 3100
          name: metrics
        - containerPort: 9095
          name: grpc
        volumeMounts:
        - mountPath: /etc/loki/config/
          name: loki-config
          readOnly: false
        - mountPath: /tmp/loki
          name: storage
          readOnly: false
      volumes:
      - configMap:
          name: loki-config
        name: loki-config
      - emptyDir: {}
        name: storage

