# permissions for end users to view lokistacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lokistack-viewer-role
rules:
- apiGroups:
  - loki.openshift.io
  resources:
  - lokistacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - loki.openshift.io
  resources:
  - lokistacks/status
  verbs:
  - get
